import { useEffect, useState } from "react";
import { api } from "../api";
import type { Company, CompanyMessage } from "../api/types";

export default function ChatsPage() {
  const [companies, setCompanies] = useState<Company[]>([]);
  const [selected, setSelected] = useState<Company | null>(null);
  const [messages, setMessages] = useState<CompanyMessage[]>([]);
  const [text, setText] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { api.listMyCompanies().then((result) => { setCompanies(result.items.filter((item) => item.status === "active")); setSelected(result.items.find((item) => item.status === "active") ?? null); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Не удалось загрузить чаты")); }, []);
  useEffect(() => { if (!selected) return; api.listCompanyMessages(selected.id).then((result) => setMessages(result.items)).catch((caught) => setError(caught instanceof Error ? caught.message : "Не удалось загрузить сообщения")); }, [selected?.id]);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !text.trim()) return; try { const message = await api.sendCompanyMessage(selected.id, text); setMessages((items) => [...items, message]); setText(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Не удалось отправить сообщение"); } };
  return <main className="mx-auto max-w-[1240px] px-5 py-10 lg:px-8"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#69826e]">Общение</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Мои чаты</h1></div><section className="grid min-h-[620px] overflow-hidden rounded-[30px] border border-[#dce5da] bg-white shadow-[0_18px_50px_rgba(35,65,42,.08)] md:grid-cols-[330px_1fr]"><aside className="border-b border-[#dce5da] bg-[#f7faf5] md:border-b-0 md:border-r"><div className="border-b border-[#dce5da] px-5 py-4"><h2 className="font-extrabold">Компании</h2></div>{companies.length ? companies.map((company) => <button key={company.id} onClick={() => setSelected(company)} className={`flex w-full items-center gap-3 border-b border-[#e5ece3] px-5 py-4 text-left ${selected?.id === company.id ? "bg-[#e7f8c9]" : "hover:bg-white"}`}><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#102318] text-sm font-black text-[#bdf238]">{company.name.slice(0, 1)}</span><span className="min-w-0"><b className="block truncate text-sm">{company.name}</b><span className="mt-1 block truncate text-xs text-[#718075]">{company.membersCount} участников</span></span></button>) : <p className="p-5 text-sm text-[#718075]">Вы пока не состоите в компаниях.</p>}</aside><div className="flex min-h-[420px] flex-col">{selected ? <><header className="flex items-center gap-3 border-b border-[#dce5da] px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#102318] text-sm font-black text-[#bdf238]">{selected.name.slice(0, 1)}</span><div><h2 className="font-extrabold">{selected.name}</h2><p className="text-xs text-[#718075]">Чат компании</p></div></header><div className="flex-1 space-y-3 overflow-y-auto bg-[#f7faf5] p-5">{messages.length ? messages.map((message) => <article key={message.id} className="max-w-[85%] rounded-2xl bg-white px-4 py-3 shadow-sm"><p className="text-xs font-extrabold text-[#416949]">{message.author.firstName} {message.author.lastName ?? ""}</p><p className="mt-1 text-sm leading-5">{message.text}</p></article>) : <p className="pt-24 text-center text-sm text-[#718075]">Начните разговор с участниками компании.</p>}</div><form onSubmit={send} className="flex gap-3 border-t border-[#dce5da] p-4"><input value={text} onChange={(e) => setText(e.target.value)} maxLength={2000} placeholder="Напишите сообщение" className="min-w-0 flex-1 rounded-xl border border-[#dce5da] bg-[#fbfcfa] px-4 py-3 text-sm outline-none focus:border-[#86b92e]"/><button className="rounded-xl bg-[#102318] px-5 text-sm font-bold text-[#bdf238]">Отправить</button></form></> : <p className="m-auto text-sm text-[#718075]">Выберите компанию слева.</p>}</div></section>{error && <p className="mt-4 rounded-xl bg-[#fff0ed] px-4 py-3 text-sm font-semibold text-[#9e3128]">{error}</p>}</main>;
}
